### ISSUE TITLE
Updates for Dash v1

### ISSUE THREAD

**Issue by tcbegley** [facultyai/dash-bootstrap-components#142]
This issue is for tracking changes that either need to be made, or can't be made before the release of Dash v1.  Most of the changes are the result of Dash v1 (or specifically *dash-renderer*) supporting React 16, while the current release of Dash does not.

- [x] Upgrade to reactstrap 8. Currently blocked from doing so as the implementation of some of the components we rely on (notably `Dropdown` which we use in `DropdownMenu`) has switched to using `createPortal` which is React 16 only.
- [x] Add [modals](https://reactstrap.github.io/components/modals/) (reactstrap uses `createPortal` for this). Resolved by #146 
- [x] Add [spinners](https://reactstrap.github.io/components/spinners/) (new in reactstrap 7). Resolved by #161 
- [ ] Add [toggles](https://reactstrap.github.io/components/form/#Custom-Inputs) (new in reactstrap 7). See #136. This probably means figuring out how to provide an interface to custom inputs more generally.
- [ ] Add [toasts](https://reactstrap.github.io/components/toasts/).
- [ ] Re-enable up direction in `DropdownMenu`. See #65 
- [x] Add right alignment option to `DropdownMenu`. Resolved by #143, thanks @jmsblah!

There are pre-releases out for the v1 series of Dash libraries, so we can already build much of this and test against those then release when they are released. I have a `dash-v1` branch open, I propose any of the above changes are PR'd against and merged into that branch.

**Comment by happyshows** [comment]
just curious, do you find any post / issue talking about the roadmap of Dash and when v1 will be ready?

**Comment by tcbegley** [comment]
[This issue](https://github.com/plotly/dash/issues/469) on the Dash repo is tracking progress on v1.

**Comment by tcbegley** [comment]
With the release of Dash v0.41.0, *dash-renderer* is now using React 16, so we are no longer blocked from implementing the items in this issue.

**Comment by happyshows** [comment]
cool, look forward to it.

**Comment by tcbegley** [comment]
There's now nothing blocking these updates, going to open individual issues for the remaining items.

**Comment by happyshows** [comment]
@tcbegley #136 is also closed, just want to highlight the visibility.

Also, regarding the toggle, is it possible to add below as well
https://getbootstrap.com/docs/4.0/components/buttons/#toggle-states
```
<div class="btn-group btn-group-toggle" data-toggle="buttons">
  <label class="btn btn-secondary active">
    <input type="radio" name="options" id="option1" autocomplete="off" checked> Active
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option2" autocomplete="off"> Radio
  </label>
  <label class="btn btn-secondary">
    <input type="radio" name="options" id="option3" autocomplete="off"> Radio
  </label>
</div>
```

**Comment by tcbegley** [comment]
Hey @happyshows 

The toggle switches are being tracked under #184 now, it will be part of a bigger effort to support custom inputs.

As far as I can tell, the `data-toggle` attribute isn't supported by reactstrap, which is what we've build *dash-bootstrap-components* on top of. We might be able build in support for this ourselves, though for now you could achieve the same sort of thing by writing your own callback. Something like

```python
app.layout = dbc.Button("Toggle", id="toggle")

@app.callback(Output("toggle", "active"), [Input("toggle", "n_clicks")])
def set_toggle(n):
    if n:
        # set active if button has been pressed odd number of times
        return n % 2 == 0
    return False
```

or for the button group

```python
app.layout = dbc.ButtonGroup(
    [
        dbc.Button(label.capitalize(), id=label)
        for label in ["left", "middle", "right"]
    ]
)

@app.callback(
    [Output(label, "active") for label in ["left", "middle", "right"]],
    [Input(label, "n_clicks") for label in ["left", "middle", "right"]],
)
def set_group_toggle(*args):
    ctx = dash.callback_context

    if not ctx.triggered or all(arg is None for arg in args):
        return [False, False, False]

    button_id = ctx.triggered[0]["prop_id"].split(".")[0]

    return [button_id == label for label in ["left", "middle", "right"]]
```
